### ISSUE TITLE
On disk format for courses

### ISSUE THREAD

**Issue by anandology** [pipalacademy/riyaz#10]
Propose and finalize on disk for authoring courses.

Format for `course.yml`:
```yaml
name: sample-course # required
title: Sample Course # required

short_description: This is a sample course for use to clarify the course.yml format # optional
description: | # required, markdown
    This is a longer description in markdown format. The course instructor can use codeblocks and italics to highlight
    the ideas in the course. 

authors:
    - alfa # we'll find an authors/alfa.md
    - bravo # authors/bravo.md

outline: # could be called 'chapters' ?
    - name: getting-started
      title: Getting started
      lessons:
        - getting-started/how-to-use-sample.md
        - getting-started/more-about-sample.md
    - name: intermediate-sample:
      title: Intermediate Sample
      lessons:
        - intermediate-sample/more-use-cases-of-sample.md
        - intermediate-sample/more-reading-about-sample.md
```

**Comment by anandology** [comment]
We may be able to reuse some of the structure from monschool-website repo.

https://github.com/fossunited/monschool-website/blob/main/courses/self-hosting-101/course.yml

**Comment by nikochiko** [comment]
I feel, after what we discussed, the outline definition in `course.yml` is repetitive. If an author wants to move a chapter from one module to another, they would have to both change the YAML and move the chapter.md file to another directory.
One way to get around this is to use a `draft: true` in the top yaml. We can use the directory structure to infer modules and chapters. Further sub-directories won't be considered.
Another way would be to let the authors structure it themselves by mentioning the paths to lessons (like the monschool website).

**Comment by anandology** [comment]
>  If an author wants to move a chapter from one module to another, they would have to both change the YAML and move the chapter.md file to another directory.

I think that is fine. 

It is good to have a single place to look at the structure of the course and course.yml is serving that purpose. It is okay to having to change in two places in the rare case of moving lessons around. 

> One way to get around this is to use a draft: true in the top yaml. 

How would that help? 

> We can use the directory structure to infer modules and chapters. Further sub-directories won't be considered.

The issue is that the ordering can't be specified. 

>  Another way would be to let the authors structure it themselves by mentioning the paths to lessons (like the monschool website).

I didn't get this. Can you please explain?

**Comment by nikochiko** [comment]
> The issue is that the ordering can't be specified.

I completely lost track of that.

> I didn't get this. Can you please explain?

Like how it is done in the monschool YAML, author will have to give the complete path to the lesson file, and can mix and match.
```yaml
chapters:
  - name: week0
    title: "Week 0: Getting Started"
    description: Some reading material will be shared to ignite interest in Self Hosting.
    lessons:
      - week0/why-self-host.md
      - week0/what-things-can-you-self-host.md
      - week0/course-outline.md
```

I think this or the one we discussed are both good enough.

**Comment by nikochiko** [comment]
Lessons are saved as markdown files.
Title of lessons will be the first h1 of the lesson, or defaulting to the title-cased version of the filename.

The course.yml should look like:
```yaml
name: sample-course # required
title: Sample Course # required

short_description: This is a sample course for use to clarify the course.yml format # optional
description: | # required, markdown
    This is a longer description in markdown format. The course instructor can use codeblocks and italics to highlight
    the ideas in the course. 

authors:
    - alfa # we'll find an authors/alfa.md
    - bravo # authors/bravo.md

outline: # could be called 'chapters' ?
    - getting-started:
        - how-to-use-sample
        - more-about-sample
    - intermediate-sample:
        - more-use-cases-of-sample
        - more-reading-about-sample
```

I think one disadvantage with doing it like this is that it becomes harder to set the module titles to something else.
like if we want to have a module called "Why self host?" with a question mark, we would have to make some special arrangement.
One idea that came up during our discussions was another YAML dictionary for mapping names to titles. With a key called "chapters" or "modules".
I think either that, or we could structure outline like:
```yaml
outline:
  - why-self-host:
      title: "Why self Host?"
      lessons:
        - lesson-1
        - lesson-2
        - lesson-3
```

But then I think it would make sense to just use a separate key for the `name` as well rather than use it as the key itself. i.e.
```yaml
outline:
  - name: why-self-host
    title: "Why self host?"
    lessons:
      - lesson-1
      - lesson-2
      - lesson-3

What do you think?
```
