### ISSUE TITLE
Course Development Flow

### ISSUE THREAD

**Issue by anandology** [pipalacademy/riyaz#4]
This issue outlines the flow for developing a course.

The course creator will start a new course by calling the following commands:

```
$ pip install riyaz

$ riyaz new course_directory
```

That would create a course structure with a couple of sample lessons and a course.yml file.

You can start a dev server using:

```
$ riyaz serve
http://localhost:5000/
```

The dev server would serve the course and any changes made to the lessons will be reloaded live. The behavior is similar to mkdocs.

**Comment by anandology** [comment]
The course structure:

```
course.yml
assets/
authors/
    alice.md
    bob.md
course/
   getting-started/
       welcome.md
       circle-and-rectangles.md
       lines-and-polygons.md
   styles/
     basic-styles.md
     web-colors.md
```

**Comment by anandology** [comment]
The course.yml will be of the following format:

```
slug: the-joy-of-programming
title: The Joy of Programming
short_description: Learn programming the fun way.
description: |
    The Joy of programming course introduces programming to absolute beginners by making them draw interesting shapes and patterns using Python.

outline:
    - getting-started:
           - welcome
           - circle-and-rectangles
           - lines-and-polygons
    - styles:
           - basic-styles
           -  web-colors

authors:
    - alice
    - bob
```

The author file will be in the following format:

```
name: Alice Something
photo: assets/alice.png
---

Alice has been developing and teaching Python from many years.
```

Please note that the outline will just list the basename of the file without `.md` extension. The title of the lesson will be inferred from heading 1 of the markdown.
